package utils

const (
	ErrorFirebaseEmailMissing         = "no firebase email available"
	ErrorBlockedEmailDomain           = "blocked-email-domain"
	ErrorNotExistentTranslation       = "not-existent-translation"
	ErrorPublishedContent             = "cannot-remove-published-content"
	ErrorResourceNotFound             = "resource-not-found"
	ErrorBookNotFound                 = "book-not-found"
	ErrorUnmatchedUser                = "unmatched-user"
	ErrorEmptyArray                   = "empty-array-provided"
	ErrorEmptyBook                    = "empty-book-provided"
	ErrorAnalyticsPlatformUnsupported = "unsupported-platform"
	ErrorAnalyticsEventUnsupported    = "unsupported-event_type"
	ErrorInvalidObjectId              = "invalid-object-id"
	ErrorSubSubscriptionNotFound      = "subscription-not-found"
	ErrorSubAlreadyExists             = "subscription-already-in-database"
	ErrorSubOwnedByOtherUser          = "subscription-owned-by-different-user"
	ErrorUserNotFound                 = "user-not-found"
	ErrorCMSRightsNeeded              = "request-need-cms-access"
	ErrorCMSAdminRightsNeeded         = "request-need-cms-admin-access"
	ErrorBookCurrentNotFilled         = "book-current-not-filled"
	ErrorIntercomEventUnsupported     = "unsupported-intercom-event_type"
	ErrorRequiresSubscription         = "requires_subscription"
	ErrorPublishedContentWithoutDate  = "published-contents-must-have-a-publish-date"
	ErrorSlugPresent                  = "slug-not-unique"
	ErrorConcurrency                  = "record-was-already-changed"
	ErrorSubscriptionItemPlanNotFound = "subscription-item-plan-not-found"
)
