apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparta-ms---service-name--
  namespace: 4books-sparta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparta-ms---service--name
  template:
    metadata:
      namespace: 4books-sparta
      labels:
        app: sparta-ms---service-name--
    spec:
      initContainers:
        - name: migrations
          imagePullPolicy: Never
          image: books4_ms_--service-name--_migrations:latest
          env:
            - name: DB_HOST
              value: "pg-minikube-postgresql.default.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_SSL
              value: "disable"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: "localpw"
            - name: DB_NAME
              value: "books4_ms_--service-name--"
            - name: DB_OPEN
              value: "60"
      terminationGracePeriodSeconds: 101
      containers:
      - name: sparta-ms---service-name--
        image: books4_ms_--service-name--:latest
        command: ["sparta_ms_--service-name--", "gateway"]
        imagePullPolicy: Never
        lifecycle:
          preStop:
            exec:
              command: ["sleep","90"]
        ports:
          - name: sparta-ms---service-name--
            containerPort: 8101
        readinessProbe:
          httpGet:
            path: /_probe
            port: sparta-ms---service-name--
          initialDelaySeconds: 30
          periodSeconds: 2
          timeoutSeconds: 3
          failureThreshold: 5
          successThreshold: 5
        resources:
          requests:
            cpu: 400m
            memory: 400Mi
        env:
          - name: PORT
            value: "8101"
          - name: DB_HOST
            value: "pg-minikube-postgresql.default.svc.cluster.local"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: localpw
          - name: DB_NAME
            value: "books4_ms_--service-name--"
          - name: DB_OPEN
            value: "60"
          - name: SENTRY_DSN
            value: https://fabcc61e50cf4e79b3668daac3a3f079:9e63395291fe430087729240ad31a3a2@sentry.io/1474728

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
